// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: pkg/events/auth.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthRegistered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipient     string                 `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRegistered) Reset() {
	*x = AuthRegistered{}
	mi := &file_pkg_events_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRegistered) ProtoMessage() {}

func (x *AuthRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_events_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRegistered.ProtoReflect.Descriptor instead.
func (*AuthRegistered) Descriptor() ([]byte, []int) {
	return file_pkg_events_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRegistered) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *AuthRegistered) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_pkg_events_auth_proto protoreflect.FileDescriptor

const file_pkg_events_auth_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/events/auth.proto\x12\x06events\"D\n" +
	"\x0eAuthRegistered\x12\x1c\n" +
	"\trecipient\x18\x01 \x01(\tR\trecipient\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05tokenB?Z=github.com/ritchieridanko/apotekly-api/auth/pkg/events;eventsb\x06proto3"

var (
	file_pkg_events_auth_proto_rawDescOnce sync.Once
	file_pkg_events_auth_proto_rawDescData []byte
)

func file_pkg_events_auth_proto_rawDescGZIP() []byte {
	file_pkg_events_auth_proto_rawDescOnce.Do(func() {
		file_pkg_events_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_events_auth_proto_rawDesc), len(file_pkg_events_auth_proto_rawDesc)))
	})
	return file_pkg_events_auth_proto_rawDescData
}

var file_pkg_events_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_events_auth_proto_goTypes = []any{
	(*AuthRegistered)(nil), // 0: events.AuthRegistered
}
var file_pkg_events_auth_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_events_auth_proto_init() }
func file_pkg_events_auth_proto_init() {
	if File_pkg_events_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_events_auth_proto_rawDesc), len(file_pkg_events_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_events_auth_proto_goTypes,
		DependencyIndexes: file_pkg_events_auth_proto_depIdxs,
		MessageInfos:      file_pkg_events_auth_proto_msgTypes,
	}.Build()
	File_pkg_events_auth_proto = out.File
	file_pkg_events_auth_proto_goTypes = nil
	file_pkg_events_auth_proto_depIdxs = nil
}
