# === Variables ===
BINARY_DIR := bin
SERVER_BIN := $(BINARY_DIR)/server

# === Server Commands ===
run-server:
	go run cmd/server/main.go

build-server:
	go build -o $(SERVER_BIN) cmd/server/main.go